# Generated by Django 4.1.1 on 2022-10-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteachinguser',
            name='academic_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicdegree', verbose_name='Academic degree'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='academic_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academictitle', verbose_name='Academic title'),
        ),
    ]
