# Generated by Django 4.1.1 on 2022-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_squashed_0003_pteachinguser_created_at_pteachinguser_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteachinguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='supportteachinguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supportteachinguser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated at'),
        ),
    ]
