# Generated by Django 4.1.1 on 2022-10-17 02:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_squashed_0002_alter_academicdegree_table_alter_academictitle_table'),
        ('account', '0004_alter_pteachinguser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteachinguser',
            name='academic_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicdegree', verbose_name='Academic degree'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='academic_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academictitle', verbose_name='Academic title'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='contract_term',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Contract term'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='end_term',
            field=models.DateField(blank=True, null=True, verbose_name='End term'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='part_of_stake',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Part of stake'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='post',
            field=models.CharField(blank=True, choices=[('assistant', 'Assistant'), ('high_teacher', 'High teacher'), ('docent', 'Docent'), ('professor', 'Professor')], max_length=128, null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='start_term',
            field=models.DateField(blank=True, null=True, verbose_name='Start term'),
        ),
        migrations.AlterField(
            model_name='pteachinguser',
            name='total_teaching_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total teaching experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Avatar'),
        ),
    ]
